version: "3"
services:
  mongo:
    image: mongo:3.2.4
    container_name: mongoserver
    ports:
    - 27017:27017
    networks:
      - intra-network
    
  spring-boot-mongo-docker:
    image: tirodrigues/starwars
    ports:
    - 8080:8080
    links:
    - mongo
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"
    networks:
      - intra-network

networks:
  intra-network:
    driver: bridge
